chat/chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('rooms/', include('rooms.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat/rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'

urlpatterns = [
    path('', views.RoomListView.as_view(), name='room_list'),
    path('room/<str:room_name>/', views.RoomDetailView.as_view(), name='room_detail'),
]

chat/users/urls.py
from django.urls import path
from .views import login_view

urlpatterns = [
    path('login/', login_view, name='login'),
]

chat/chat/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

chat/rooms/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='static/room_logos/', blank=True, null=True)
    description = models.TextField()
    allowed_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='rooms', blank=True)

chat/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.utils.translation import gettext_lazy as _
from rooms.models import Room

# Create your models here.
class User(AbstractUser):
    groups = models.ManyToManyField(
        Group,
        related_name="custom_user_set",
        blank=True,
        help_text=_(
            "The groups this user belongs to. A user will get all permissions "
            "granted to each of their groups."
        ),
        verbose_name=_("groups"),
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name="custom_user_set",
        blank=True,
        help_text=_("Specific permissions for this user."),
        verbose_name=_("user permissions"),
    )
    

class Message(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='messages')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

chat/chat/views.py
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

def home(request):
    if request.user.is_authenticated:
        return redirect('/rooms/')
    else:
        return redirect('/accounts/login/')

chat/rooms/views.py
from django.views.generic import ListView, DetailView
from .models import Room
from users.models import Message

class RoomListView(ListView):
    model = Room
    template_name = 'rooms/room_list.html'

class RoomDetailView(DetailView):
    model = Room
    template_name = 'rooms/room_detail.html'
    slug_field = 'name'
    slug_url_kwarg = 'room_name'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['messages'] = Message.objects.filter(room=self.object).order_by('timestamp')
        context['rooms']= Room.objects.all()
        context['current_room_name'] = self.object.name
        return context

chat/users/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def login_view(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return HttpResponse('Logged in successfully')
        else:
            return HttpResponse('Invalid credentials', status=401)
    else:
        return HttpResponse('Invalid request', status=400)

chat/templates/base_generic.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
    <header>
        <!-- Add your header here -->
    </header>

    <main>
        {% block content %}
        <!-- Content will be inserted here -->
        {% endblock %}
    </main>

    <footer>
        <!-- Add your footer here -->
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

chat/templates/rooms/room_detail.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<div id="gradient-div" style="position: fixed; width: 5%; height: 100%; background: linear-gradient(180deg, #27617B 10%, #F3CE93 59%, #FFE0AB 73%, #FFE0AB 87%, #DAB984 100%), linear-gradient(54deg, rgba(128.92, 43.33, 43.33, 0) 0%, rgba(39, 97, 123, 0.66) 100%), linear-gradient(142deg, rgba(0, 0, 0, 0) 0%, rgba(47, 149, 118, 0.52) 100%); box-shadow: 12.600000381469727px 12.600000381469727px 12.600000381469727px; filter: blur(12.60px); left: 0; top: 0; z-index: 2;">
    <div class="room-logos">
        {% for room in rooms %}
            <img class="room-logo" src="{% static 'room_logos/'|add:room.name|stringformat:"s"|add:'.jpg' %}" alt="{{ room.name }}">
        {% endfor %}
    </div>
</div>
    <style>
        body {
            
            background: linear-gradient(217deg, #27617B 0%, #2F9576 100%);
            background-attachment: fixed;
        }
        #header {
            text-decoration-color: white;
            text-align: center;
            padding: 20px;
            position: fixed;
            width: 100%;
            height: auto;
            left: 0;
            top: 0;
            z-index: 1;
            background-color: white;
        }

        #chat-log {
            padding-top: 60px; /* Adjust this value as needed */
        }
        #header h2 {
            color: black;
        }
        #logo {
            position: fixed;
            top: 0;
            left: 0;
            width: 50px;
            height: 50px;
            border-radius: 50%; /* Make the logo circular */
    z-index: 2; /* Ensure the logo stays on top */
        }
        .room-logos {
            display: flex;
            flex-direction: column;
            margin-left: 0;
        }
        .message {
            background-color: white;
            text-decoration-color: black;
            border-radius: 10px;
            padding: 10px;
            margin-bottom: 10px;
            width: auto; /* Make the message boxes cover the full width of the screen on mobile devices */
            clear: both; /* Clear the float property to prevent overlapping messages */
        }

        .message strong {
            display: block; /* Make the username take up the full width of its parent */

        }

        @media (min-width: 600px) {
            .message {
                width: 50%; /* Make the message boxes half the width of the screen on larger devices */
            }
        }
        .message.other {
            text-align: left;
            float: left; /* Align the messages from other users to the left */
            width: 68%;
        }
        .message.self {
            /* Align the messages from the current user to the right */
            float: right; /* Align the messages from the current user to the right */
            width: 68%;
        }
.message.other strong {
    text-align: left; /* Align the username to the left for .message.other */
}

.message.self strong {
    text-align: right; /* Align the username to the right for .message.self */
}
#gradient-div {
        position: fixed;
        width: 5px; /* Set the width of the gradient div */
        height: 100%;
        /* Other styles... */
        z-index: -1;
    }
        .timestamp {
            font-size: 0.8em;
        }
        #post-message{
            z-index: 2;
            display:flex;
            justify-content: space-between;
            position:fixed;
            bottom: 0;
            width:100%;
            border:1px;
        }
        #post-message input[type="text"] {
            width: 100%;
            padding: 10px;
            border-radius: 10px;
            margin: 10px 0;
            display: inline-block;
            background-color: #a5e2ff;
        }
        #post-message button {
            width: 5%;
        }
        /* Add a left margin with sky blue color */

        #logo img {
        width: 100%;
        height: 100%;
        border-radius: 50%;
        object-fit: cover; /* This will ensure that the image covers the entire area of the div without stretching */
    }
    </style>


<div id="header" style="position: fixed; width: 100%; height: auto; left: 0; top: 0; z-index: 1;background-color:white ;float: right;">
    <h2 style="text-align: center;">{{ room.name }}</h2>
</div>

<div id="logo" style="position: fixed; width: 5%; height: 10%; left: 0;">
    <img src="{% static 'room_logos/'|add:room.name|stringformat:"s"|add:'.jpg' %}" alt="Logo" style="width: 100%; height: 100%; border-radius: 50%; object-fit: cover;">
</div>

<div id="chat-log" style="margin-left: 10%;">
    <div id="chat-log">
        {% for message in messages %}
            <div class="message {% if message.user == user %}self{% else %}other{% endif %}">
                {% if message.user != user %}
                    <strong>{{ message.user.username }}</strong>
                {% endif %}
                {{ message.content }}
                <div class="timestamp">{{ message.timestamp }}</div>
            </div>
        {% endfor %}
    </div>
</div>

    <form id="post-message">
        <input type="text" id="message-input" placeholder="Enter your awesome message here">
        <input type="hidden" id="user-id" value="{{ user.id }}">
        <input type="hidden" id="room-id" value="{{ room.id }}">
        <button type="submit">Send</button>
    </form>

    <!-- WebSocket scripts -->
    <script>
        // Connect to the WebSocket
        var socket = new WebSocket(
    'ws://' + window.location.host +
    '/ws/room/{{ room.name }}/'
);

// Connect to the WebSocket
var socket = new WebSocket('ws://' + window.location.host + '/ws/room/{{ room.name }}/');
var roomId = document.querySelector('#room-id').value;
var chatLog = document.querySelector('#chat-log'); // Define chatLog here

// Create a list of fonts
var fonts = ['Arial', 'Verdana', 'Courier', 'Times New Roman', 'Georgia'];

// Assign a font to each user when they start a session
var userFont = fonts[Math.floor(Math.random() * fonts.length)];
sessionStorage.setItem('userFont', userFont);

socket.onmessage = function(e) {
    var data = JSON.parse(e.data);
    console.log(data);

    var message = data['message'];
    var messageColorClass;

    var userId = parseInt(document.querySelector('#user-id').value); // Parse userId as integer

    console.log('userId:', userId);
    console.log('data[\'user_id\']:', data['userId']);

    if (data['userId'] === userId) {
        messageColorClass = 'self';
    } else {
        messageColorClass = 'other';
    }

    var timestamp = new Date(data['timestamp']);
    var formattedTimestamp = timestamp.toLocaleString('en-US', {
        hour: 'numeric',
        minute: 'numeric',
        hour12: true,
        day: 'numeric',
        month: 'long',
        year: 'numeric'
    });

    // Create a new message element
    var messageElem = document.createElement('div');
    messageElem.classList.add('message', messageColorClass); // Add message and color class

    // Set the font of the message to the user's font
    messageElem.style.fontFamily = sessionStorage.getItem('userFont');

    // Create strong element for username
    var usernameElem = document.createElement('strong');
    
    usernameElem.style.display = 'block'; // Add this line

    // Create div for timestamp
    var timestampElem = document.createElement('div');
    timestampElem.classList.add('timestamp');
    timestampElem.textContent = formattedTimestamp;
    
    // Create text node for message content
    var messageContent = document.createTextNode(message);
    
    // Append username, message content, and timestamp to message element
    messageElem.appendChild(usernameElem);
    messageElem.appendChild(messageContent);
    messageElem.appendChild(timestampElem);

    // Append username, message content, and timestamp to message element
    if (data['userId'] != userId) {
        usernameElem.textContent = data['username'];
    }
    messageElem.appendChild(messageContent);
    messageElem.appendChild(timestampElem);

    // Add the message to the chat log
    chatLog.appendChild(messageElem);

    // Scroll to the bottom of the chat log
    chatLog.scrollTop = chatLog.scrollHeight;
};

// Other WebSocket event handlers...


socket.onclose = function(e) {
    console.error('Chat socket closed unexpectedly');
};

document.querySelector('#post-message').onsubmit = function(e) {
    e.preventDefault();

    // Retrieve the input field's value
    var messageInputDom = document.querySelector('#message-input');
    var message = messageInputDom.value;

    // Retrieve the user ID and room ID
    var userId = document.querySelector('#user-id').value;
    var roomId = document.querySelector('#room-id').value;

    // Get the current timestamp
    var timestamp = new Date().toISOString();

    // Send the message to the server
    socket.send(JSON.stringify({
        'message': message,
        'user_id': userId,
        'room_id': roomId,
        'timestamp': timestamp
    }));

    // Clear the input field and focus it
    messageInputDom.value = '';
    messageInputDom.focus();
};


    </script>
{% endblock %}

chat/templates/rooms/room_list.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
    <style>
        .card-img-top {
            width: 100%;
            height: 200px; /* Adjust this value to change the height of the images */
            object-fit: cover;
            object-position: center;
            border: 1px solid black;
        }
    </style>
    <div class="container">
        <div class="jumbotron text-center">
            <h1>Welcome back, {{ request.user.username }}</h1>
        </div>
        <div class="row">
            {% for room in object_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <img class="card-img-top" src="{% static 'room_logos/'|add:room.name|add:'.jpg' %}" alt="Room logo">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{% url 'rooms:room_detail' room.name %}">{{ room.name }}</a>
                            </h5>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 and not forloop.last %}
                    </div><div class="row">
                {% endif %}
            {% empty %}
                <div class="col-12">
                    <p>No rooms available.</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}